samples: "samples.tsv"
units: "units.tsv"

reference:
  c3: "data/input/shared_assets/genomes/C3_assembly.fa"
  neff: "data/input/shared_assets/genomes/Neff_assembly.fa"

annot:
  c3: "data/input/shared_assets/annotations/C3_annotations.gff"
  neff: "data/input/shared_assets/annotations/Neff_.gff"

enzyme: "DpnII"

neff_v1:
  genome: 'data/input/shared_assets/genomes/NEFF_v1.fa'
  annot: 'data/input/shared_assets/annotations/NEFF_v1.43.gff'

n_cpus: 12

contact_maps:
  max_res: 2000
  med_res : 8000
  low_res: 20000

loops:
    min-dist: 4000
    max-dist: 2000000

borders:
    min-dist: 0
    max-dist: 0

rnaseq_li2020: "data/input/shared_assets/rnaseq/li2020/li2020_table2.xlsx"

params:
  hicstuff_iteralign: "--read-len 150 --aligner bowtie2"
  bowtie2: "--sensitive-local"
