samples: "samples.tsv"
units: "units.tsv"

reference: "data/input/genome/C3.fa"
annot: "data/input/annotations/c3_annotations/Acanthamoeba_castellanii.gff3"
enzyme: "DpnII"

neff:
  genome: 'data/input/genome/NEFF_v1.fa'
  annot: 'data/input/annotations/NEFF_v1.43.gff'

n_cpus: 12

contact_maps:
  max_res: 2000
  med_res : 8000
  low_res: 20000

loops_small:
    min-dist: 4000
    max-dist: 2000000

borders:
    min-dist: 0
    max-dist: 0

rnaseq: "data/input/diff_expr/li2020_table2.xlsx"

params:
  hicstuff_iteralign: "--read-len 150 --aligner bowtie2"
  bowtie2: "--sensitive-local"
