samples: "samples.tsv"
units: "units.tsv"

reference:
  c3: "data/input/genome/C3.fa"
  neff: "data/input/genome/Neff.fa"

annot:
  c3: "data/input/annotations/c3_annotations/Acanthamoeba_castellanii_C3.gff3"
  neff: "data/input/annotations/neff_annotations/Acanthamoeba_castellanii_Neff.gff3"

enzyme: "DpnII"

neff_v1:
  genome: 'data/input/genome/NEFF_v1.fa'
  annot: 'data/input/annotations/NEFF_v1.43.gff'

n_cpus: 12

contact_maps:
  max_res: 2000
  med_res : 8000
  low_res: 20000

loops:
    min-dist: 4000
    max-dist: 2000000

borders:
    min-dist: 0
    max-dist: 0

rnaseq_li2020: "data/input/diff_expr/li2020_table2.xlsx"

params:
  hicstuff_iteralign: "--read-len 150 --aligner bowtie2"
  bowtie2: "--sensitive-local"
