samples: "samples.tsv"
units: "units.tsv"

reference: "data/input/genome/C3.fa"
enzyme: "DpnII"

n_cpus: 12

contact_maps:
  max_res: 2000
  med_res : 8000
  low_res: 20000

loops_small:
    min-dist: 8000
    max-dist: 2000000

borders:
    min-dist: 0
    max-dist: 0

params:
  hicstuff_iteralign: "--read-len 150 --aligner bowtie2"
  bowtie2: "--sensitive-local"
